// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddAccount(arg1:string,arg2:string,arg3:number):Promise<models.Account>;

export function AddCategory(arg1:string,arg2:string,arg3:any):Promise<models.Category>;

export function AddTransaction(arg1:string,arg2:number,arg3:string,arg4:string,arg5:number,arg6:number,arg7:string,arg8:string):Promise<models.Transaction>;

export function GetAccounts():Promise<Array<models.Account>>;

export function GetCategories():Promise<Array<models.Category>>;

export function GetTransactions():Promise<Array<models.Transaction>>;

export function Greet(arg1:string):Promise<string>;
